title: Long Long ago
email: yarco.wang@gmail.com

baseurl: ""
url: https://www.bbish.net/

highlighter: rouge
permalink: /posts/:year:month:day/:title:output_ext
theme: minima

# host: 127.0.0.1
# port: 34000
